export const BEGIN_FILE_DRAG = "BEGIN_FILE_DRAG";
export const END_FILE_DRAG = "END_FILE_DRAG";
export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const FROM_EMAIL_VALIDATE = "FROM_EMAIL_VALIDATE";
export const TO_EMAIL_VALIDATE = "TO_EMAIL_VALIDATE";
export const SEND_WAITING = "SEND_WAITING";
export const SEND_COMPLETE = "SEND_COMPLETE";

export const CHANGE_FROM_NAME = "CHANGE_FROM_NAME";
export const CHANGE_FROM_EMAIL = "CHANGE_FROM_EMAIL";
export const CHANGE_TO_NAME = "CHANGE_TO_NAME";
export const CHANGE_TO_EMAIL = "CHANGE_TO_EMAIL";
export const CHANGE_SUBJECT = "CHANGE_SUBJECT";
export const CHANGE_TEXT = "CHANGE_TEXT";
export const CHANGE_TOTAL_ATTACHMENTS_SIZE = "CHANGE_TOTAL_ATTACHMENTS_SIZE";
export const ADD_TRACK = "ADD_TRACK";
export const UPDATE_TRACK_STATUS = "UPDATE_TRACK_STATUS";
